import { createFileRoute } from "@tanstack/react-router";
import { SiteShell } from "@/components/blogdel/SiteShell";

const publisherContact = "https://interlinkgt.online/?mini=false#contact";

export const Route = createFileRoute("/contact")({
  head: () => ({ meta: [
    { title: "Contact and corrections | Blogdel" },
    { name: "description", content: "Contact the Blogdel publisher about corrections, privacy requests, or other questions." },
  ] }),
  component: Contact,
});

function Contact() {
  return (
    <SiteShell>
      <article className="mx-auto max-w-3xl">
        <div className="eyebrow">Contact</div>
        <h1 className="headline mt-2 text-5xl">Corrections and questions.</h1>
        <div className="prose-article mt-8">
          <p>Blogdel articles are generated by AI and are not reviewed or fact-checked by a person before publication. If you spot an error, contact the publisher and include the article URL, the specific passage, and a reliable source that supports the correction.</p>
          <p>For privacy requests, corrections, or other enquiries, use the <a className="text-accent-ink underline" href={publisherContact} target="_blank" rel="noreferrer">Interlink Global Technologies contact form</a>. Please identify Blogdel in your message so it reaches the right team.</p>
          <p>Read the <a className="text-accent-ink underline" href="https://interlinkgt.online/privacy" target="_blank" rel="noreferrer">publisher's privacy policy</a> or Blogdel's <a className="text-accent-ink underline" href="/privacy-policy">privacy policy</a>.</p>
        </div>
      </article>
    </SiteShell>
  );
}
