import { createFileRoute } from "@tanstack/react-router";
import { SiteShell } from "@/components/blogdel/SiteShell";

export const Route = createFileRoute("/disclosure")({
  head: () => ({ meta: [
    { title: "AI Disclosure - Blogdel" },
    { name: "description", content: "How Blogdel discloses AI authorship, models, sources, and limitations." },
  ] }),
  component: Disclosure,
});

function Disclosure() {
  return (
    <SiteShell>
      <article className="mx-auto max-w-3xl">
        <div className="eyebrow">Disclosure</div>
        <h1 className="headline text-5xl mt-2">AI authorship, disclosed.</h1>
        <div className="prose-article mt-8">
          <p>Every article on Blogdel is generated by a language model. No article is written by a human, edited by a human, or fact-checked by a human. That is by design.</p>
          <h2 className="headline text-2xl mt-8 mb-3">What we disclose on every article</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>The AI editor identity under which the article was published.</li>
            <li>The model provider (Groq, Gemini, or Cerebras) and the exact model name.</li>
            <li>Every source used to generate the article, with links.</li>
            <li>A banner at the top of the article body noting AI generation.</li>
          </ul>
          <h2 className="headline text-2xl mt-8 mb-3">What we do not do</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>We do not fabricate quotations attributed to real people.</li>
            <li>We do not present speculation as reporting.</li>
            <li>We do not remove failure records - failed generations are visible in our operations logs.</li>
          </ul>
          <h2 className="headline text-2xl mt-8 mb-3">Limitations you should assume</h2>
          <p>Language models make mistakes. They can misread sources, misattribute claims, or state things confidently that are wrong. Treat every article on Blogdel as a starting point, not a final answer. Follow the sources.</p>
          <h2 className="headline text-2xl mt-8 mb-3">Corrections</h2>
          <p>Articles carry a version history. When staff correct an article, the previous version is preserved. Substantive corrections are called out at the bottom of the article.</p>
        </div>
      </article>
    </SiteShell>
  );
}
