import { Link } from "@tanstack/react-router";
import { Search } from "lucide-react";

const NAV = [
  { slug: "technology", label: "Technology" },
  { slug: "health", label: "Health" },
  { slug: "sports", label: "Sports" },
  { slug: "politics", label: "Politics" },
  { slug: "entertainment", label: "Entertainment" },
  { slug: "business", label: "Business" },
  { slug: "science", label: "Science" },
  { slug: "education", label: "Education" },
  { slug: "food", label: "Food" },
  { slug: "history", label: "History" },
];

export function SiteHeader() {
  const now = new Date();
  return (
    <header className="border-b border-border bg-background">
      <div className="mx-auto max-w-7xl px-4">
        <div className="flex items-center justify-between py-3 text-xs uppercase tracking-widest text-muted-foreground">
          <span>{now.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}</span>
          <span className="hidden sm:inline">Autonomous Editorial · Vol. 1</span>
        </div>
        <div className="relative flex flex-col items-center gap-2 border-t border-b border-border py-6">
          <Link to="/" className="headline text-5xl md:text-6xl">Blogdel</Link>
          <p className="text-xs uppercase tracking-[0.3em] text-muted-foreground">An autonomous editorial publication</p>
          <Link to="/readme" className="headline mt-2 inline-flex min-h-10 items-center justify-center bg-black px-5 py-2 text-base text-white transition-colors hover:bg-neutral-800 sm:absolute sm:right-0 sm:top-1/2 sm:mt-0 sm:-translate-y-1/2">Read Me</Link>
        </div>
        <nav className="flex items-center justify-between gap-3 py-3">
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm">
            <Link to="/blogs" className="font-medium hover:text-accent-ink">All</Link>
            {NAV.map(n => <Link key={n.slug} to="/category/$slug" params={{ slug: n.slug }} className="text-muted-foreground hover:text-foreground">{n.label}</Link>)}
          </div>
          <Link to="/search" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"><Search className="h-4 w-4" />Search</Link>
        </nav>
      </div>
    </header>
  );
}

export function SiteFooter() {
  return (
    <footer className="mt-16 border-t border-border bg-background">
      <div className="mx-auto max-w-7xl px-4 py-10 text-sm text-muted-foreground">
        <div className="flex flex-col gap-4 md:flex-row md:justify-between">
          <div>
            <div className="headline text-2xl text-foreground">Blogdel</div>
            <p className="mt-2 max-w-md">Blogdel is an autonomous editorial publication. Every article is generated by AI from disclosed sources and validated against a strict schema.</p>
          </div>
          <div className="flex flex-wrap gap-x-6 gap-y-2">
            <Link to="/about" className="hover:text-foreground">About</Link>
            <Link to="/disclosure" className="hover:text-foreground">AI disclosure</Link>
            <Link to="/blogs" className="hover:text-foreground">All articles</Link>
          </div>
        </div>
        <div className="mt-6 border-t border-border pt-4 text-xs">© {new Date().getFullYear()} Blogdel. Generated by machines. Read with a critical eye.</div>
      </div>
    </footer>
  );
}

export function SiteShell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-background text-foreground"><SiteHeader /><main className="mx-auto max-w-7xl px-4 py-10">{children}</main><SiteFooter /></div>;
}
